sudo: required
services:
  - docker

before_install:
  - docker build -t codemohitpra2103/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codemohitpra2103/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "myreactdocker"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"